### ISSUE TITLE
What's the difference between laravel intellisense and Laravel Snippets?

### ISSUE THREAD

**Issue by moyus** [simoebenhida/laravel-intellisense#19]
As title.

**Comment by simoebenhida** [comment]
They are too different! Here is some example so you can get the difference:

Laravel snippets:
- It creates snippets like if you write `Route` it helps you write the whole route code format instead of tapping everything!

Laravel intellisense:
- It gives you autocomplete for model attributes/ route name / etc (Like you see on the Readme examples)
